Inspiration.create(quote: "Keep love in your heart. A life without it is like a sunless garden when the flowers are dead.", author: "Oscar Wilde", themename: "Love", theme_id: 1)
Inspiration.create(quote: "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.", author: "Lao Tzu", themename: "Love", theme_id: 1)
Inspiration.create(quote: "Love is composed of a single soul inhabiting two bodies.", author: "Aristotle", themename: "Love", theme_id: 1)
Inspiration.create(quote: "I have decided to stick with love. Hate is too great a burden to bear.", author: "Martin Luther King, Jr.", themename: "Love", theme_id: 1)
Inspiration.create(quote: "We're born alone, we live alone, we die alone. Only through our love and friendship can we create the illusion for the moment that we're not alone.", author: "Orson Welles", themename: "Love", theme_id: 1)
Inspiration.create(quote: "A loving heart is the beginning of all knowledge.", author: "Mother Theresa", themename: "Love", theme_id: 1)
Inspiration.create(quote: "For it was not into my ear you whispered, but into my heart. It was not my lips you kissed, but my soul.", author: "Judy Garland", themename: "Love", theme_id: 1)
Inspiration.create(quote: "I was born with an enormous need for affection, and a terrible need to give it.", author: "Audrey Hepburn", themename: "Love", theme_id: 1)
Inspiration.create(quote: "At the touch of love everyone becomes a poet.", author: "Plato", themename: "Love", theme_id: 1)
Inspiration.create(quote: "Love makes your soul crawl out from its hiding place.", author: "Zora Neale Hurston", themename: "Love", theme_id: 1)
Inspiration.create(quote: "Take care of your body. It's the only place you have to live.", author: "Jim Rohn", themename: "Fitness", theme_id: 2)
Inspiration.create(quote: "Exercise to stimulate, not to annihilate. The world wasn't formed in a day, and neither were we. Set small goals and build upon them.", author: "Lee Haney", themename: "Fitness", theme_id: 2)
Inspiration.create(quote: "Unless you puke, faint, or die, keep going.", author: "Jillian Michaels", themename: "Fitness", theme_id: 2)
Inspiration.create(quote: "Your body is the church where Nature asks to be reverenced.", author: "Marquis de Sade", themename: "Fitness", theme_id: 2)
Inspiration.create(quote: "Health is the thing that makes you feel that now is the best time of the year.", author: "Franklin P. Adams", themename: "Fitness", theme_id: 2)
Inspiration.create(quote: "Exercise should be regarded as tribute to the heart.", author: "Gene Tunnel", themename: "Fitness", theme_id: 2)
Inspiration.create(quote: "Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway.", author: "Earl Nightingale", themename: "Fitness", theme_id: 2)
Inspiration.create(quote: "When you feel like quitting, think about why you started.", author: "nil", themename: "Fitness", theme_id: 2)
Inspiration.create(quote: "Don’t wish for it, work for it.", author: "nil", themename: "Fitness", theme_id: 2)
Inspiration.create(quote: "Rather than aiming for being perfect, aim for being better than you were yesterday.", author: "nil", themename: "Fitness", theme_id: 2)
Inspiration.create(quote: "If you're going through hell, keep going.", author: "Winston Churchill", themename: "Motivational", theme_id: 3)
Inspiration.create(quote: "Even if you fall on your face, you're still moving forward.", author: "Victor Kiam", themename: "Motivational", theme_id: 3)
Inspiration.create(quote: "Who seeks shall find.", author: "Sophocles", themename: "Motivational", theme_id: 3)
Inspiration.create(quote: "If you want to conquer fear, don't sit home and think about it. Go out and get busy.", author: "Dale Carnegie", themename: "Motivational", theme_id: 3)
Inspiration.create(quote: "I'd rather attempt to do something great and fail than to attempt to do nothing and succeed.", author: "Robert H. Schuller", themename: "Motivational", theme_id: 3)
Inspiration.create(quote: "Opportunity does not knock, it presents itself when you beat down the door.", author: "Kyle Chandler", themename: "Motivational", theme_id: 3)
Inspiration.create(quote: "Problems are not stop signs, they are guidelines.", author: "Robert H. Schuller", themename: "Motivational", theme_id: 3)
Inspiration.create(quote: "The harder the conflict, the more glorious the triumph.", author: "Thomas Paine", themename: "Motivational", theme_id: 3)
Inspiration.create(quote: "Ever tried. Ever failed. No matter. Try Again. Fail again. Fail better.", author: "Samuel Beckett", themename: "Motivational", theme_id: 3)
Inspiration.create(quote: "Never complain and never explain.", author: "Benjamin Disraeli", themename: "Motivational", theme_id: 3)
Inspiration.create(quote: "I’m convinced that about half of what separates the successful entrepreneurs from the non-successful ones is pure perseverance.", author: "Steve Jobs", themename: "Entrepreneurship", theme_id: 4)
Inspiration.create(quote: "Openly share and talk to people about your idea. Use their lack of interest or doubt to fuel your motivation to make it happen", author: "Todd Garland, Founder of BuySellAds", themename: "Entrepreneurship", theme_id: 4)
Inspiration.create(quote: "You shouldn’t focus on why you can’t do something, which is what most people do. You should focus on why perhaps you can, and be one of the exceptions.", author: "Steve Case, Co-Founder of AOL", themename: "Entrepreneurship", theme_id: 4)
Inspiration.create(quote: "I have not failed. I’ve just found 10,000 ways that won’t work.", author: "Thomas Edison", themename: "Entrepreneurship", theme_id: 4)
Inspiration.create(quote: "Out there in some garage is an entrepreneur who’s forging a bullet with your company’s name on it.", author: "Gary Hamel, Founder of Strategos", themename: "Entrepreneurship", theme_id: 4)
Inspiration.create(quote: "If things seem under control, you’re just not going fast enough.", author: "Mario Andretti", themename: "Entrepreneurship", theme_id: 4)
Inspiration.create(quote: "The higher you go in a company, the less oxygen there is, so supporting intelligent life becomes difficult.", author: "Guy Kawasaki", themename: "Entrepreneurship", theme_id: 4)
Inspiration.create(quote: "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do. So throw off the bowlines. Sail away from the safe harbor. Catch the trade winds in your sails. Explore. Dream. Discover.", author: "Mark Twain", themename: "Entrepreneurship", theme_id: 4)
Inspiration.create(quote: "Entrepreneurship is living a few years of your life like most people won't so you can spend the rest of your life like most people can't.", author: "Student of Warren G. Tracy", themename: "Entrepreneurship", theme_id: 4)
Inspiration.create(quote: "Failure defeats losers, failure inspires winners.", author: "Robert T. Kiyosaki", themename: "Entrepreneurship", theme_id: 4)
Inspiration.create(quote: "Happiness is when what you think, what you say, and what you do are in harmony.", author: "Mahatma Gandhi", themename: "Happiness", theme_id: 5)
Inspiration.create(quote: "Don't wait around for other people to be happy for you. Any happiness you get you've got to make yourself.", author: "Alice Walker", themename: "Happiness", theme_id: 5)
Inspiration.create(quote: "Never let a bad day make you feel like you have a bad life.", author: "nil", themename: "Happiness", theme_id: 5)
Inspiration.create(quote: "Happiness is not something you postpone for the future; it is somethingyou design into the present.", author: "", themename: "Happiness", theme_id: 5)
Inspiration.create(quote: "Each morning when I open my eyes I say to myself: I, not events, have the power to make me happy or unhappy today. I can choose which it shall be. Yesterday is dead, tomorrow hasn't arrived yet. I have just one day, today, and I'm going to be happy in it.", author: "Groucho Marx", themename: "Happiness", theme_id: 5)
Inspiration.create(quote: "To be happy, we must not be too concerned with others.", author: "Albert Camus", themename: "Happiness", theme_id: 5)
Inspiration.create(quote: "When one door of happiness closes, another opens, but often we look so long at the closed door that we do not see the one that has been opened for us.", author: "Hellen Keller", themename: "Happiness", theme_id: 5)
Inspiration.create(quote: "Learn to let go. That is the key to happiness.", author: "Buddha", themename: "Happiness", theme_id: 5)
Inspiration.create(quote: "Worry never robs tomorrow of its sorrow. It only saps today of its joy.", author: "Leo Buscaglia", themename: "Happiness", theme_id: 5)
Inspiration.create(quote: "Life will bring you pain all by itself. Your responsibility is to create joy.", author: "Milton Erickson", themename: "Happiness", theme_id: 5)
Theme.create(name: "Love")
Theme.create(name: "Fitness")
Theme.create(name: "Motivational")
Theme.create(name: "Entrepreneurship")
Theme.create(name: "Happiness")
Theme.create(name: "Custom")
puts "SUCK A DICK"